#!/bin/bash

# This script removes the annoying issue of the double shell:
# one is your user and other is gdm user ( zombie shell )
# see here for more info
# https://bugzilla.gnome.org/show_bug.cgi?id=782832

#This check if automaticlogin is enable and apply the script only if yes
grep -q "AutomaticLoginEnable=True" /etc/gdm/custom.conf || pkill -KILL -u gdm

