#!/usr/bin/env bash

dconf dump / | grep '\[org/gnome/shell/extensions/materialshell/layouts\]' -q || dconf load / < /usr/share/gnome-shell/extensions/material-shell@papyelgringo/schemas/10_material-shell.gschema.override
dconf dump / | grep '\[org/gnome/shell/extensions/pop-shell\]' -q || dconf load / < /usr/share/gnome-shell/extensions/pop-shell\@system76.com/schemas/10_pop-shell.gschema.override
