#!/bin/bash

# Makes the GNOME Shell Apps Dashboard sort the apps into their
#   respective categories based on the FreeDesktop standard.

# Lincensed under the GPL License.

app=manjaro-app-folders

INSTALL() {
gsettings set org.gnome.desktop.app-folders folder-children "['accessories', 'office', 'system-tools']"

gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/accessories/ name "Accessories"
gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/accessories/ categories "['Utility']"
gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/accessories/ apps "['yad-icon-browser.desktop', 'uget-gtk.desktop']"
gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/accessories/ translate true

gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/office/ name "Office"
gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/office/ categories "['Office']"
gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/office/ translate true

gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/system-tools/ name "System Tools"
gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/system-tools/ categories "['System', 'Settings']"
gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/system-tools/ apps "['qvidcap.desktop', 'qv4l2.desktop', 'bssh.desktop', 'bvnc.desktop', 'hp-uiscan.desktop']"
gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/system-tools/ translate true

#Remove the .desktop entry in HOME user folder
if [[ -e $HOME/.config/autostart/$app.desktop ]]; then
	rm $HOME/.config/autostart/$app.desktop
fi
}

REMOVE() {
gsettings reset-recursively org.gnome.desktop.app-folders
}

USAGE() {
	echo
    echo "Usage: you need to specific an argument:"
	echo "(a)pply or (r)emove"
	echo
}

if [[ ${@} == 0 ]]; then
	USAGE
	exit 1
else case ${@} in
	a|A) INSTALL ;;
	r|R) REMOVE ;;
	*) USAGE ;;
	esac
fi
